spring:
  profiles:
    group:
      dev: dev
      prod: prod
      local: local
---
# common data.
common: common-data

jwt:
  secretKey: testSecretKey20230327testSecretKey20230327testSecretKey20230327

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    show-sql: true
    hibernate:
        ddl-auto: update
        show-sql: true
  security:
    csrf:
      enabled: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      hibernate:
        SQL:
          debug
        type:
          descriptor:
            sql:
              BasicBinder: debug
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
---
spring.config.activate.on-profile: dev
test:
  a: 100
  b: 100

---
spring.config.activate.on-profile: prod

test:
  a: 200
  b: 200
---
spring.config.activate.on-profile: local

test:
  a: 300
  b: 300